name: nuclearDevice
main: sadmean.mc.nuclearDevice.nuclearDevice
version: 0.9
author: Choelian

commands:
  nuclearDevice:
    description: Inferfaces with nuclearDevice
    usage: /nuclearDevice [args]